//
//  DictionaryData.swift
//  Feen
//
//  Created by Made Vidyatma Adhi Krisna on 11/03/26.
//

import Foundation

let dictsData: [Dictionaries] = [

Dictionaries(title: "Absolute Advantage", description: "Ability of an individual or country to produce a good more efficiently than another."),
Dictionaries(title: "Accounting Equation", description: "Assets = Liabilities + Equity."),
Dictionaries(title: "Acid Test Ratio", description: "Liquidity ratio that measures ability to pay short-term liabilities."),
Dictionaries(title: "Amortization", description: "Gradual reduction of a debt over time through regular payments."),
Dictionaries(title: "Annual Revenue", description: "Total income generated by a business in a year."),

Dictionaries(title: "Balance Sheet", description: "Financial statement showing assets, liabilities, and equity."),
Dictionaries(title: "Bankruptcy", description: "Legal process when an entity cannot repay debts."),
Dictionaries(title: "Bond", description: "Debt investment where an investor loans money to an entity."),
Dictionaries(title: "Budget", description: "Plan for managing income and expenses."),
Dictionaries(title: "Bull Market", description: "Market condition where prices are rising."),

Dictionaries(title: "Capital Gain", description: "Profit from selling an asset at a higher price."),
Dictionaries(title: "Cash Flow", description: "Movement of money in and out of a business."),
Dictionaries(title: "Collateral", description: "Asset pledged to secure a loan."),
Dictionaries(title: "Compound Interest", description: "Interest calculated on the initial principal and accumulated interest."),
Dictionaries(title: "Credit Score", description: "Number representing creditworthiness."),

Dictionaries(title: "Debt", description: "Money borrowed that must be repaid."),
Dictionaries(title: "Default", description: "Failure to repay a loan."),
Dictionaries(title: "Depreciation", description: "Reduction in value of an asset over time."),
Dictionaries(title: "Dividend", description: "Payment made by a company to shareholders."),
Dictionaries(title: "Diversification", description: "Strategy of spreading investments across assets."),

Dictionaries(title: "Earnings", description: "Profit of a company after expenses."),
Dictionaries(title: "Economic Growth", description: "Increase in the production of goods and services."),
Dictionaries(title: "Equity", description: "Ownership interest in a company."),
Dictionaries(title: "Exchange Rate", description: "Value of one currency relative to another."),
Dictionaries(title: "Expense Ratio", description: "Annual fee charged by investment funds."),

Dictionaries(title: "Financial Statement", description: "Formal record of financial activities."),
Dictionaries(title: "Fiscal Policy", description: "Government policy regarding taxation and spending."),
Dictionaries(title: "Fixed Asset", description: "Long-term tangible asset used in operations."),
Dictionaries(title: "Fixed Cost", description: "Cost that does not change with production."),
Dictionaries(title: "Foreign Exchange", description: "Market where currencies are traded."),

Dictionaries(title: "GDP", description: "Gross Domestic Product measuring economic output."),
Dictionaries(title: "Gross Profit", description: "Revenue minus cost of goods sold."),
Dictionaries(title: "Growth Stock", description: "Stock expected to grow faster than market."),
Dictionaries(title: "Government Bond", description: "Debt security issued by a government."),
Dictionaries(title: "Global Market", description: "International trading of goods and assets."),

Dictionaries(title: "Hedge Fund", description: "Investment fund using diverse strategies."),
Dictionaries(title: "Holding Company", description: "Company that owns other companies."),
Dictionaries(title: "High Yield Bond", description: "Bond offering higher interest due to higher risk."),
Dictionaries(title: "Housing Market", description: "Market related to buying and selling houses."),
Dictionaries(title: "Human Capital", description: "Economic value of workforce skills."),

Dictionaries(title: "Inflation", description: "Increase in prices over time."),
Dictionaries(title: "Interest Rate", description: "Percentage charged for borrowing money."),
Dictionaries(title: "Investment", description: "Asset purchased with expectation of future return."),
Dictionaries(title: "Index Fund", description: "Fund designed to track a market index."),
Dictionaries(title: "Income Statement", description: "Financial report showing profit and loss."),

Dictionaries(title: "Joint Venture", description: "Business arrangement between two parties."),
Dictionaries(title: "Junk Bond", description: "Bond with high risk and high return."),
Dictionaries(title: "Job Market", description: "Market where employers seek employees."),
Dictionaries(title: "Just-in-Time Inventory", description: "Inventory strategy reducing storage costs."),
Dictionaries(title: "Jurisdiction Tax", description: "Tax rules within a specific region."),

Dictionaries(title: "Key Rate", description: "Important benchmark interest rate."),
Dictionaries(title: "Key Performance Indicator", description: "Metric used to measure business success."),
Dictionaries(title: "Knowledge Economy", description: "Economy driven by information and innovation."),
Dictionaries(title: "Key Investor", description: "Major stakeholder in a company."),

Dictionaries(title: "Liquidity", description: "Ability to convert assets into cash quickly."),
Dictionaries(title: "Liability", description: "Financial obligation owed to another party."),
Dictionaries(title: "Leverage", description: "Using borrowed capital to increase investment return."),
Dictionaries(title: "Loan", description: "Borrowed money expected to be repaid."),
Dictionaries(title: "Long Term Investment", description: "Investment held for extended periods."),

Dictionaries(title: "Market Capitalization", description: "Total market value of a company's shares."),
Dictionaries(title: "Monetary Policy", description: "Central bank actions controlling money supply."),
Dictionaries(title: "Mortgage", description: "Loan used to buy property."),
Dictionaries(title: "Mutual Fund", description: "Investment vehicle pooling money from investors."),
Dictionaries(title: "Margin", description: "Difference between revenue and cost."),

Dictionaries(title: "Net Income", description: "Company profit after all expenses."),
Dictionaries(title: "Net Worth", description: "Total assets minus liabilities."),
Dictionaries(title: "Nominal Value", description: "Face value of a financial instrument."),
Dictionaries(title: "Non Performing Loan", description: "Loan where borrower fails to repay."),
Dictionaries(title: "National Debt", description: "Total government debt."),

Dictionaries(title: "Opportunity Cost", description: "Value of the next best alternative foregone."),
Dictionaries(title: "Operating Income", description: "Profit from business operations."),
Dictionaries(title: "Overdraft", description: "Bank facility allowing withdrawal beyond balance."),
Dictionaries(title: "Ownership Equity", description: "Owner's share in a business."),

Dictionaries(title: "Portfolio", description: "Collection of financial investments."),
Dictionaries(title: "Principal", description: "Original sum of money invested or borrowed."),
Dictionaries(title: "Profit Margin", description: "Percentage of revenue that is profit."),
Dictionaries(title: "Public Company", description: "Company whose shares are publicly traded."),
Dictionaries(title: "Private Equity", description: "Investment in private companies."),

Dictionaries(title: "Quantitative Easing", description: "Central bank policy injecting money into economy."),
Dictionaries(title: "Quick Ratio", description: "Liquidity ratio measuring short-term obligations."),

Dictionaries(title: "Revenue", description: "Income generated from business operations."),
Dictionaries(title: "Return on Investment", description: "Profit relative to investment cost."),
Dictionaries(title: "Risk Management", description: "Process of identifying and mitigating risks."),
Dictionaries(title: "Recession", description: "Significant decline in economic activity."),

Dictionaries(title: "Stock", description: "Ownership share in a company."),
Dictionaries(title: "Savings", description: "Income not spent and reserved for future use."),
Dictionaries(title: "Supply and Demand", description: "Economic model determining prices."),
Dictionaries(title: "Shareholder", description: "Individual who owns company shares."),
Dictionaries(title: "Subsidy", description: "Government financial support."),

Dictionaries(title: "Tax", description: "Mandatory financial charge imposed by government."),
Dictionaries(title: "Treasury Bond", description: "Long-term government debt security."),
Dictionaries(title: "Trade Deficit", description: "When imports exceed exports."),
Dictionaries(title: "Transaction Cost", description: "Cost incurred in trading assets."),

Dictionaries(title: "Unemployment Rate", description: "Percentage of unemployed labor force."),
Dictionaries(title: "Utility", description: "Satisfaction derived from consumption."),

Dictionaries(title: "Valuation", description: "Process of determining asset value."),
Dictionaries(title: "Venture Capital", description: "Funding provided to startups."),
Dictionaries(title: "Volatility", description: "Degree of variation in asset price."),

Dictionaries(title: "Wealth", description: "Total accumulated assets."),
Dictionaries(title: "Working Capital", description: "Difference between current assets and liabilities."),
Dictionaries(title: "World Bank", description: "International financial institution."),

Dictionaries(title: "Yield", description: "Income return on an investment."),

Dictionaries(title: "Zero Coupon Bond", description: "Bond that pays no interest but is sold at discount.")

]
